version: '3.2'

services:
  hio_admin:
    image: hio_admin
    container_name: hio_admin
    restart: always
    networks:
      backend:
        aliases:
          - hio_admin
    ports:
      - 5020:80
    build:
      context: .
      dockerfile: docker/Dockerfile

networks:
  backend:
    driver: bridge
